# Generated by Django 4.2.3 on 2023-08-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Admin', 'Admin')], default='Student', max_length=8, null=True),
        ),
    ]
