# Generated by Django 4.2.3 on 2023-08-01 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_created_at_course_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='video',
            new_name='audio',
        ),
    ]
